export const labels = {
  blendMode: 'Blend mode',
  cornerRadius: 'Corner radius',
  bottomLeftRadius: 'Bottom-left radius',
  bottomRightRadius: 'Bottom-right radius',
  topLeftRadius: 'Top-left radius',
  topRightRadius: 'Top-right radius',
  dimension: 'Dimension',
  height: 'Height',
  width: 'Width',
  effectsStyleId: 'Effects style',
  fill: 'Fill',
  fillsStyleId: 'Fill color style',
  fills: 'Fills',
  type: 'Layer type',
  locked: 'Locked state',
  isMask: 'Mask state',
  opacity: 'Opacity',
  rotation: 'Rotation',
  stroke: 'Stroke',
  dashPattern: 'Dash pattern',
  strokeAlign: 'Stroke align',
  strokeCap: 'Stroke cap',
  strokesStyleId: 'Stroke color style',
  strokeJoin: 'Stroke join',
  strokeWeight: 'Stroke weight',
  strokes: 'Strokes',
  text: 'Text',
  textCase: 'Case',
  fontName: 'Font',
  fontSize: 'Font size',
  letterSpacing: 'Letter-spacing',
  lineHeight: 'Line-height',
  paragraphIndent: 'Paragraph indent',
  paragraphSpacing: 'Paragraph space',
  textAlignHorizontal: 'Text align horizontal',
  textAlignVertical: 'Text align vertical',
  textDecoration: 'Text decoration',
  textStyleId: 'Text style',
  visible: 'Visibility'
}
