import { commandFactory } from './command-factory'

export const zh = commandFactory('zh')
export const cs = commandFactory('cs')
export const da = commandFactory('da')
export const nl = commandFactory('nl')
export const en = commandFactory('en')
export const fi = commandFactory('fi')
export const fr = commandFactory('fr')
export const de = commandFactory('de')
export const hi = commandFactory('hi')
export const it = commandFactory('it')
export const ja = commandFactory('ja')
export const ko = commandFactory('ko')
export const ms = commandFactory('ms')
export const no = commandFactory('no')
export const pl = commandFactory('pl')
export const pt = commandFactory('pt')
export const es = commandFactory('es')
export const sv = commandFactory('sv')
export const th = commandFactory('th')
export const tr = commandFactory('tr')
