import { mainFactory } from './main-factory'

export const zh = mainFactory('zh')
export const cs = mainFactory('cs')
export const da = mainFactory('da')
export const nl = mainFactory('nl')
export const en = mainFactory('en')
export const fi = mainFactory('fi')
export const fr = mainFactory('fr')
export const de = mainFactory('de')
export const hi = mainFactory('hi')
export const it = mainFactory('it')
export const ja = mainFactory('ja')
export const ko = mainFactory('ko')
export const ms = mainFactory('ms')
export const no = mainFactory('no')
export const pl = mainFactory('pl')
export const pt = mainFactory('pt')
export const es = mainFactory('es')
export const sv = mainFactory('sv')
export const th = mainFactory('th')
export const tr = mainFactory('tr')
